export const GROCERY_ITEMS = {
  'vegetarian': [
    { name: 'Brown Rice', amount: '2kg', price: 3.50 },
    { name: 'Lentils', amount: '1kg', price: 2.80 },
    { name: 'Spinach', amount: '500g', price: 2.00 },
    { name: 'Tomatoes', amount: '1kg', price: 3.20 },
    { name: 'Carrots', amount: '1kg', price: 1.50 },
    { name: 'Onions', amount: '1kg', price: 1.20 },
    { name: 'Eggs', amount: '12 pack', price: 3.00 },
    { name: 'Cheese', amount: '400g', price: 4.50 },
    { name: 'Bread', amount: '800g loaf', price: 2.20 },
    { name: 'Bananas', amount: '1kg', price: 1.80 },
    { name: 'Chickpeas', amount: '400g can', price: 1.20 },
    { name: 'Black Beans', amount: '400g can', price: 1.30 },
    { name: 'Tofu', amount: '400g', price: 2.50 },
    { name: 'Plant-Based Milk', amount: '1L', price: 2.60 },
    { name: 'Mushrooms', amount: '300g', price: 2.40 },
    { name: 'Zucchini', amount: '1kg', price: 3.00 },
    { name: 'Couscous', amount: '1kg', price: 2.80 },
    { name: 'Hummus', amount: '250g', price: 2.70 },
    { name: 'Bell Peppers', amount: '1kg', price: 4.20 },
    { name: 'Cucumber', amount: '2 pieces', price: 1.60 },
    { name: 'Broccoli', amount: '500g', price: 2.50 },
    { name: 'Cauliflower', amount: '1 head', price: 2.80 },
    { name: 'Soy Yogurt', amount: '500g', price: 2.50 },
    { name: 'Pumpkin Seeds', amount: '200g', price: 3.00 },
    { name: 'Sunflower Seeds', amount: '200g', price: 2.60 },
    { name: 'Oats', amount: '1kg', price: 1.80 },
    { name: 'Peanut Butter', amount: '500g', price: 3.50 },
    { name: 'Strawberries', amount: '250g', price: 2.20 },
    { name: 'Apples', amount: '1kg', price: 2.50 },
    { name: 'Oranges', amount: '1kg', price: 2.60 },
    { name: 'Grapes', amount: '500g', price: 3.00 },
    { name: 'Wholemeal Pasta', amount: '1kg', price: 2.20 },
    { name: 'Vegetable Stock', amount: '6 cubes', price: 1.20 },
    { name: 'Canned Corn', amount: '400g', price: 1.10 },
    { name: 'Green Beans', amount: '400g frozen', price: 2.00 },
    { name: 'Beetroot', amount: '400g', price: 1.90 },
    { name: 'Kale', amount: '250g', price: 2.10 },
    { name: 'Cabbage', amount: '1 head', price: 2.30 },
    { name: 'Bulgur Wheat', amount: '1kg', price: 3.20 },
    { name: 'Vegan Sausages', amount: '6 pack', price: 3.80 }
  ],
  'high-protein': [
    { name: 'Chicken Breast', amount: '1.5kg', price: 8.50 },
    { name: 'Salmon Fillets', amount: '600g', price: 12.00 },
    { name: 'Greek Yogurt', amount: '1kg', price: 4.00 },
    { name: 'Eggs', amount: '18 pack', price: 4.20 },
    { name: 'Tuna Cans', amount: '6 pack', price: 8.00 },
    { name: 'Quinoa', amount: '500g', price: 4.50 },
    { name: 'Almonds', amount: '200g', price: 3.80 },
    { name: 'Cottage Cheese', amount: '500g', price: 3.50 },
    { name: 'Sweet Potatoes', amount: '1kg', price: 2.20 },
    { name: 'Broccoli', amount: '500g', price: 2.50 },
    { name: 'Protein Bars', amount: '5 pack', price: 7.00 },
    { name: 'Whey Protein', amount: '1kg', price: 24.00 },
    { name: 'Turkey Mince', amount: '500g', price: 5.50 },
    { name: 'Lean Beef Steak', amount: '400g', price: 6.20 },
    { name: 'Tofu', amount: '400g', price: 2.50 },
    { name: 'Tempeh', amount: '250g', price: 3.00 },
    { name: 'Soy Milk (High Protein)', amount: '1L', price: 2.50 },
    { name: 'Black Beans', amount: '400g', price: 1.30 },
    { name: 'Edamame', amount: '400g frozen', price: 3.00 },
    { name: 'Peanut Butter', amount: '500g', price: 3.50 },
    { name: 'Chickpeas', amount: '400g', price: 1.20 },
    { name: 'Egg Whites', amount: '1L carton', price: 3.80 },
    { name: 'Mixed Nuts', amount: '300g', price: 4.20 },
    { name: 'Lentils', amount: '1kg', price: 2.80 },
    { name: 'Pumpkin Seeds', amount: '200g', price: 3.00 },
    { name: 'Sardines', amount: '3 pack', price: 4.00 },
    { name: 'Low-fat Cheese', amount: '500g', price: 4.00 },
    { name: 'Protein Pancake Mix', amount: '500g', price: 5.00 },
    { name: 'Protein Cereal', amount: '500g', price: 4.80 },
    { name: 'Venison Burgers', amount: '4 pack', price: 7.00 },
    { name: 'Lamb Chops', amount: '500g', price: 9.00 },
    { name: 'Bacon (Lean)', amount: '200g', price: 3.00 },
    { name: 'Baked Beans (High Protein)', amount: '400g', price: 1.80 },
    { name: 'Shrimp', amount: '400g frozen', price: 7.50 },
    { name: 'Duck Breast', amount: '400g', price: 8.50 },
    { name: 'Pork Chops', amount: '500g', price: 6.80 },
    { name: 'Protein Yogurt', amount: '4 pack', price: 4.50 },
    { name: 'Sunflower Seeds', amount: '200g', price: 2.60 },
    { name: 'Seitan', amount: '300g', price: 4.00 },
    { name: 'Mozzarella', amount: '250g', price: 2.90 }
  ],
  'low-carb': [
    { name: 'Chicken Thighs', amount: '1kg', price: 6.50 },
    { name: 'Beef Mince', amount: '750g', price: 8.00 },
    { name: 'Avocados', amount: '6 pieces', price: 6.00 },
    { name: 'Cauliflower', amount: '1 head', price: 2.80 },
    { name: 'Zucchini', amount: '1kg', price: 3.00 },
    { name: 'Bell Peppers', amount: '1kg', price: 4.20 },
    { name: 'Olive Oil', amount: '500ml', price: 5.50 },
    { name: 'Cheese', amount: '600g', price: 7.00 },
    { name: 'Eggs', amount: '12 pack', price: 3.00 },
    { name: 'Spinach', amount: '300g', price: 1.80 },
    { name: 'Bacon', amount: '200g', price: 3.00 },
    { name: 'Sausages', amount: '6 pack', price: 4.50 },
    { name: 'Broccoli', amount: '500g', price: 2.50 },
    { name: 'Asparagus', amount: '250g', price: 3.00 },
    { name: 'Mushrooms', amount: '300g', price: 2.40 },
    { name: 'Coconut Milk', amount: '400ml', price: 2.00 },
    { name: 'Ground Turkey', amount: '500g', price: 5.80 },
    { name: 'Mayonnaise (Low-carb)', amount: '400g', price: 3.60 },
    { name: 'Lettuce', amount: '2 heads', price: 2.20 },
    { name: 'Beef Steak', amount: '400g', price: 6.50 },
    { name: 'Cod Fillets', amount: '500g', price: 7.50 },
    { name: 'Prawns', amount: '300g', price: 6.00 },
    { name: 'Chia Seeds', amount: '300g', price: 4.00 },
    { name: 'Celery', amount: '1 bunch', price: 2.00 },
    { name: 'Cabbage', amount: '1 head', price: 2.30 },
    { name: 'Radishes', amount: '500g', price: 1.80 },
    { name: 'Kale', amount: '250g', price: 2.10 },
    { name: 'Eggplant', amount: '1 piece', price: 2.20 },
    { name: 'Brussels Sprouts', amount: '400g', price: 3.00 },
    { name: 'Parmesan', amount: '200g', price: 3.50 },
    { name: 'Almond Flour', amount: '500g', price: 6.00 },
    { name: 'Zoodles', amount: '300g', price: 3.80 },
    { name: 'Cauliflower Rice', amount: '400g frozen', price: 2.50 },
    { name: 'Ghee', amount: '300g', price: 4.20 },
    { name: 'Coconut Oil', amount: '500ml', price: 5.00 },
    { name: 'Sunflower Seeds', amount: '200g', price: 2.60 },
    { name: 'Walnuts', amount: '150g', price: 3.40 },
    { name: 'Hazelnuts', amount: '150g', price: 3.60 },
    { name: 'Mozzarella', amount: '250g', price: 2.90 }
  ],
  'default': [
    { name: 'Chicken Breast', amount: '1kg', price: 6.00 },
    { name: 'Ground Beef', amount: '500g', price: 5.50 },
    { name: 'Rice', amount: '2kg', price: 3.00 },
    { name: 'Pasta', amount: '1kg', price: 2.20 },
    { name: 'Potatoes', amount: '2kg', price: 2.80 },
    { name: 'Mixed Vegetables', amount: '1kg frozen', price: 3.50 },
    { name: 'Milk', amount: '2L', price: 2.40 },
    { name: 'Bread', amount: '800g loaf', price: 2.20 },
    { name: 'Eggs', amount: '12 pack', price: 3.00 },
    { name: 'Apples', amount: '1kg', price: 2.50 },
    { name: 'Orange Juice', amount: '1L', price: 2.00 },
    { name: 'Butter', amount: '250g', price: 2.20 },
    { name: 'Cheddar Cheese', amount: '300g', price: 3.40 },
    { name: 'Cereal', amount: '750g', price: 3.20 },
    { name: 'Ham Slices', amount: '150g', price: 2.30 },
    { name: 'Yogurt', amount: '4 pack', price: 3.00 },
    { name: 'Tomato Sauce', amount: '500ml', price: 1.80 },
    { name: 'Canned Tuna', amount: '3 pack', price: 4.00 },
    { name: 'Biscuits', amount: '300g', price: 2.00 },
    { name: 'Chips', amount: '150g', price: 1.50 },
    { name: 'Granola Bars', amount: '6 pack', price: 2.80 },
    { name: 'Jam', amount: '350g', price: 2.20 },
    { name: 'Peanut Butter', amount: '500g', price: 3.50 },
    { name: 'Ice Cream', amount: '1L', price: 3.00 },
    { name: 'Pizza', amount: 'frozen', price: 4.50 },
    { name: 'Canned Corn', amount: '400g', price: 1.10 },
    { name: 'Mustard', amount: '250ml', price: 1.60 },
    { name: 'Ketchup', amount: '500ml', price: 2.00 },
    { name: 'Sliced Cheese', amount: '200g', price: 2.50 },
    { name: 'Toilet Paper', amount: '6 rolls', price: 3.00 },
    { name: 'Dish Soap', amount: '750ml', price: 2.00 },
    { name: 'Paper Towels', amount: '2 rolls', price: 2.20 },
    { name: 'Tissues', amount: 'box', price: 1.50 },
    { name: 'Trash Bags', amount: '20 pack', price: 2.80 },
    { name: 'Coffee', amount: '250g', price: 3.50 },
    { name: 'Tea Bags', amount: '80 pack', price: 2.60 },
    { name: 'Sugar', amount: '1kg', price: 1.30 },
    { name: 'Salt', amount: '750g', price: 0.80 },
    { name: 'Flour', amount: '1kg', price: 1.20 }
  ]
};